x=input('Enter first string')
y=input('Enter second string')
print('Length of first string:',len(x))
print('Length of second string:',len(y))
a=len(x)
b=len(y)
print('Sum of lenght of both strings:',a+b)
